- id: git-secrets
  name: "git-secrets: scan new files"
  description: Prevents you from committing secrets and credentials into git repositories
  language: docker_image
  entry: ghcr.io/denis-trofimov/git-secrets-docker git secrets --scan 
  stages: [commit]
